---
- name: "Download the .deb file for Plex Media Server version {{ plex_server_version }}"
  get_url:
    url: "https://downloads.plex.tv/plex-media-server/{{ plex_server_version }}/plexmediaserver_{{ plex_server_version }}_amd64.deb"
    dest: "/tmp/plexmediaserver_{{ plex_server_version }}_amd64.deb"
    mode: '0644'

- name: "Install Plex Media Server version {{ plex_server_version }}"
  apt:
    deb: "/tmp/plexmediaserver_{{ plex_server_version }}_amd64.deb"
    state: 'installed'
  notify: 'restart-ansible-role-plex'

- name: 'Start the plexmediaserver daemon'
  service:
    name: 'plexmediaserver'
    state: 'started'
    enabled: 'yes'

- name: 'Create the transcoding directory that will be used by plex'
  file:
    path: "{{ plex_app_transcode_directory }}"
    state: 'directory'
    owner: 'plex'  # This user is automatically created via the plex installer
    mode: '0755'

- name: 'Create the config/library directory that will be used by plex'
  file:
    path: "{{ plex_app_library_directory }}"
    state: 'directory'
    owner: 'plex'  # This user is automatically created via the plex installer
    mode: '0755'
