---
- name: "Download the .deb file for Plex Media Server version {{ plex_server_version }}"
  get_url:
    url: "https://downloads.plex.tv/plex-media-server/{{ plex_server_version }}/plexmediaserver_{{ plex_server_version }}_amd64.deb"
    dest: "/tmp/plexmediaserver_{{ plex_server_version }}_amd64.deb"
    mode: '0644'

- name: "Install Plex Media Server version {{ plex_server_version }}"
  apt:
    deb: "/tmp/plexmediaserver_{{ plex_server_version }}_amd64.deb"
    state: 'installed'
  notify: 'restart-ansible-role-plex'

- name: 'Start the plexmediaserver daemon'
  service:
    name: 'plexmediaserver'
    state: 'started'
    enabled: 'yes'

- meta: flush_handlers
